<?php

/*
Component: Application Form
File Path: app/Filament/Resources/ApplicationResource/Schemas/ApplicationForm.php
Company: Ygrace Tech
Author: Ibrahim Olalekan

Purpose:
Defines the Filament form schema for applications.
Primarily used for officer review or restricted edits.
Applicants create applications via the public portal.

Status: ✅ Production Ready (namespace corrected)
Version: 1.7 (Filament v3 compatible)
*/

namespace App\Filament\Resources\ApplicationResource\Schemas;

use Filament\Schemas\Schema;
use Filament\Forms\Components\Section;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Select;

class ApplicationForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make('Application Details')
                    ->schema([
                        TextInput::make('application_number')
                            ->label('Application No.')
                            ->disabled(), // immutable, generated by system

                        TextInput::make('user.name')
                            ->label('Applicant')
                            ->disabled(), // applicant name is linked to user

                        Select::make('programme_id')
                            ->label('Programme')
                            ->relationship('programme', 'name')
                            ->searchable()
                            ->disabled(), // programme chosen by applicant

                        Select::make('status')
                            ->label('Status')
                            ->options([
                                'pending'   => 'Pending',
                                'reviewed'  => 'Reviewed',
                                'accepted'  => 'Accepted',
                                'rejected'  => 'Rejected',
                            ])
                            ->required(),
                    ]),
            ]);
    }
}
